source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'TEST_TEXT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TEST_TEXT
pod 'YYKit'
pod 'Masonry'
pod 'OC_CWCarousel'
#pod 'Bugly'  ,'2.5.5'      
#  pod 'TalkfunSDKFramework', '~> 5.3.8'       #欢拓SDK
#  pod 'MJRefresh', '~> 3.1.15.7'   
end
